version: '2'
services:
  helloword:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
     - .:/home/app/helloword
     - /home/jales/node-docker/node_modules